### ISSUE TITLE
Implement Reddit authentication

### ISSUE THREAD

**Issue by asn007** [rTeenDeveloper/hub#4]
Reddit authentication logic is awaiting!
What should it do:

1. Check if user is already authenticated
2. If the user is authenticated:
  - Check if user has a slack account bound
  - If yes: rebind account for now
  - If no: bind a Reddit account to this user
3. If the user is not authenticated:
  - Check if we have the user with those slack credentials. If yes, authenticate them
  - If no - create an account with username of new user being username of Reddit account
  - Authenticate the user with that account

**Comment by MatejMecka** [comment]
#23 is in progress.

**Comment by xrisk** [comment]
Will need more work once the Mongo connector is finished...

**Comment by xrisk** [comment]
Specifically, querying the DB for authentication and binding reddit accounts to new/existing accounts.
